-- -----------------------------------------------------------------------
-- E-Digital — Import des pages WP (Option A : templates PHP fidèles).
-- Généré automatiquement par wp-theme-edigital/sql/build-theme.py
-- Chaque page pointe vers un template dans wp-content/themes/edigital/templates/.
-- Idempotent : re-exécuter le fichier supprime puis recrée les pages.
-- -----------------------------------------------------------------------

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Nettoyage préalable des pages E-Digital déjà présentes.
DELETE pm FROM wp_postmeta pm INNER JOIN wp_posts p ON p.ID = pm.post_id WHERE p.post_name IN ('accueil', 'services', 'service-creation-web', 'service-mobile-native', 'service-app-metier', 'service-branding', 'service-visibilite-seo', 'service-visibilite-google-ads', 'service-maintenance', 'nos-technologies', 'nos-projets', 'blog', 'contact', 'accueil-menu-item', 'services-menu-item', 'service-creation-web-menu-item', 'service-mobile-native-menu-item', 'service-app-metier-menu-item', 'service-branding-menu-item', 'service-visibilite-seo-menu-item', 'service-visibilite-google-ads-menu-item', 'service-maintenance-menu-item', 'nos-technologies-menu-item', 'nos-projets-menu-item', 'blog-menu-item', 'contact-menu-item') AND p.post_type IN ('page','nav_menu_item');
DELETE FROM wp_posts WHERE post_name IN ('accueil', 'services', 'service-creation-web', 'service-mobile-native', 'service-app-metier', 'service-branding', 'service-visibilite-seo', 'service-visibilite-google-ads', 'service-maintenance', 'nos-technologies', 'nos-projets', 'blog', 'contact', 'accueil-menu-item', 'services-menu-item', 'service-creation-web-menu-item', 'service-mobile-native-menu-item', 'service-app-metier-menu-item', 'service-branding-menu-item', 'service-visibilite-seo-menu-item', 'service-visibilite-google-ads-menu-item', 'service-maintenance-menu-item', 'nos-technologies-menu-item', 'nos-projets-menu-item', 'blog-menu-item', 'contact-menu-item') AND post_type IN ('page','nav_menu_item');

-- Nettoyage du menu principal.
DELETE tr FROM wp_term_relationships tr INNER JOIN wp_term_taxonomy tt ON tt.term_taxonomy_id = tr.term_taxonomy_id INNER JOIN wp_terms t ON t.term_id = tt.term_id WHERE tt.taxonomy = 'nav_menu' AND t.slug = 'edigital-primary';
DELETE tt FROM wp_term_taxonomy tt INNER JOIN wp_terms t ON t.term_id = tt.term_id WHERE tt.taxonomy = 'nav_menu' AND t.slug = 'edigital-primary';
DELETE FROM wp_terms WHERE slug = 'edigital-primary';

-- Pages (contenu minimal + template PHP assigné).
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10001, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-accueil.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Accueil', '', 'publish', 'closed', 'closed', '', 'accueil', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 1, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10001, '_wp_page_template', 'templates/page-accueil.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10002, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-services.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Nos Services', '', 'publish', 'closed', 'closed', '', 'services', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 2, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10002, '_wp_page_template', 'templates/page-services.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10003, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-creation-web.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Création de Site Web', '', 'publish', 'closed', 'closed', '', 'service-creation-web', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 3, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10003, '_wp_page_template', 'templates/page-service-creation-web.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10004, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-mobile-native.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Applications Mobiles Natives', '', 'publish', 'closed', 'closed', '', 'service-mobile-native', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 4, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10004, '_wp_page_template', 'templates/page-service-mobile-native.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10005, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-app-metier.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Applications Métier', '', 'publish', 'closed', 'closed', '', 'service-app-metier', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 5, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10005, '_wp_page_template', 'templates/page-service-app-metier.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10006, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-branding.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Branding & Design', '', 'publish', 'closed', 'closed', '', 'service-branding', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 6, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10006, '_wp_page_template', 'templates/page-service-branding.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10007, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-visibilite-seo.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Visibilité SEO & Référencement Naturel', '', 'publish', 'closed', 'closed', '', 'service-visibilite-seo', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 7, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10007, '_wp_page_template', 'templates/page-service-visibilite-seo.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10008, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-visibilite-google-ads.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Publicité Google Ads & Meta Ads', '', 'publish', 'closed', 'closed', '', 'service-visibilite-google-ads', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 8, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10008, '_wp_page_template', 'templates/page-service-visibilite-google-ads.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10009, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-service-maintenance.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Maintenance & Support Technique', '', 'publish', 'closed', 'closed', '', 'service-maintenance', '', '', NOW(), UTC_TIMESTAMP(), '', 10002, '', 9, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10009, '_wp_page_template', 'templates/page-service-maintenance.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10010, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-nos-technologies.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Nos Technologies', '', 'publish', 'closed', 'closed', '', 'nos-technologies', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 10, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10010, '_wp_page_template', 'templates/page-nos-technologies.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10011, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-nos-projets.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Nos Projets', '', 'publish', 'closed', 'closed', '', 'nos-projets', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 11, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10011, '_wp_page_template', 'templates/page-nos-projets.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10012, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-blog.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Blog', '', 'publish', 'closed', 'closed', '', 'blog', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 12, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10012, '_wp_page_template', 'templates/page-blog.php');
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (10013, 1, NOW(), UTC_TIMESTAMP(), '<!-- wp:paragraph --><p><em>Le rendu visuel de cette page est fourni par le template <code>templates/page-contact.php</code>. Modifier la structure se fait directement dans le fichier PHP du thème.</em></p><!-- /wp:paragraph -->', 'Contact', '', 'publish', 'closed', 'closed', '', 'contact', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 13, 'page', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (10013, '_wp_page_template', 'templates/page-contact.php');

INSERT INTO wp_options (option_name, option_value, autoload) VALUES ('page_for_posts', '10012', 'yes') ON DUPLICATE KEY UPDATE option_value='10012';

-- Menu principal E-Digital.
INSERT INTO wp_terms (term_id, name, slug, term_group) VALUES (9000, 'E-Digital Primary', 'edigital-primary', 0);
INSERT INTO wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (9000, 9000, 'nav_menu', '', 0, 0);
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (11001, 1, NOW(), UTC_TIMESTAMP(), '', ' ', '', 'publish', 'closed', 'closed', '', 'accueil-menu-item', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 1, 'nav_menu_item', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (11001, '_menu_item_type', 'post_type'), (11001, '_menu_item_menu_item_parent', '0'), (11001, '_menu_item_object_id', '10001'), (11001, '_menu_item_object', 'page'), (11001, '_menu_item_target', ''), (11001, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'), (11001, '_menu_item_xfn', ''), (11001, '_menu_item_url', '');
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (11001, 9000, 0);
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (11002, 1, NOW(), UTC_TIMESTAMP(), '', ' ', '', 'publish', 'closed', 'closed', '', 'services-menu-item', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 2, 'nav_menu_item', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (11002, '_menu_item_type', 'post_type'), (11002, '_menu_item_menu_item_parent', '0'), (11002, '_menu_item_object_id', '10002'), (11002, '_menu_item_object', 'page'), (11002, '_menu_item_target', ''), (11002, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'), (11002, '_menu_item_xfn', ''), (11002, '_menu_item_url', '');
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (11002, 9000, 0);
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (11003, 1, NOW(), UTC_TIMESTAMP(), '', ' ', '', 'publish', 'closed', 'closed', '', 'nos-technologies-menu-item', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 10, 'nav_menu_item', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (11003, '_menu_item_type', 'post_type'), (11003, '_menu_item_menu_item_parent', '0'), (11003, '_menu_item_object_id', '10010'), (11003, '_menu_item_object', 'page'), (11003, '_menu_item_target', ''), (11003, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'), (11003, '_menu_item_xfn', ''), (11003, '_menu_item_url', '');
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (11003, 9000, 0);
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (11004, 1, NOW(), UTC_TIMESTAMP(), '', ' ', '', 'publish', 'closed', 'closed', '', 'nos-projets-menu-item', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 11, 'nav_menu_item', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (11004, '_menu_item_type', 'post_type'), (11004, '_menu_item_menu_item_parent', '0'), (11004, '_menu_item_object_id', '10011'), (11004, '_menu_item_object', 'page'), (11004, '_menu_item_target', ''), (11004, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'), (11004, '_menu_item_xfn', ''), (11004, '_menu_item_url', '');
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (11004, 9000, 0);
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (11005, 1, NOW(), UTC_TIMESTAMP(), '', ' ', '', 'publish', 'closed', 'closed', '', 'blog-menu-item', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 12, 'nav_menu_item', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (11005, '_menu_item_type', 'post_type'), (11005, '_menu_item_menu_item_parent', '0'), (11005, '_menu_item_object_id', '10012'), (11005, '_menu_item_object', 'page'), (11005, '_menu_item_target', ''), (11005, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'), (11005, '_menu_item_xfn', ''), (11005, '_menu_item_url', '');
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (11005, 9000, 0);
INSERT INTO wp_posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (11006, 1, NOW(), UTC_TIMESTAMP(), '', ' ', '', 'publish', 'closed', 'closed', '', 'contact-menu-item', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 13, 'nav_menu_item', '', 0);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (11006, '_menu_item_type', 'post_type'), (11006, '_menu_item_menu_item_parent', '0'), (11006, '_menu_item_object_id', '10013'), (11006, '_menu_item_object', 'page'), (11006, '_menu_item_target', ''), (11006, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'), (11006, '_menu_item_xfn', ''), (11006, '_menu_item_url', '');
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (11006, 9000, 0);
UPDATE wp_term_taxonomy SET count = (SELECT COUNT(*) FROM wp_term_relationships WHERE term_taxonomy_id = 9000) WHERE term_taxonomy_id = 9000;

INSERT INTO wp_options (option_name, option_value, autoload) VALUES ('permalink_structure', '/%postname%/', 'yes') ON DUPLICATE KEY UPDATE option_value='/%postname%/';

SET FOREIGN_KEY_CHECKS = 1;

